### ISSUE TITLE
[申請人工文章判定] [資訊量不足] Discussion from pongpong507

### ISSUE THREAD

**Issue by pongpong507** [NCU-GS4538-Linux/Linux-Community#123]
原文被AI評價為「資訊量不足」
原文網址：https://github.com/NCU-GS4538-Linux/Linux-Community/discussions/122
原文內容：
簡單來說，MQTT就是：
![MQTT meme](https://github.com/NCU-GS4538-Linux/Linux-Community/assets/91622406/3f2f39cb-53cb-4bc2-9584-087ae276e729)

欸對沒錯
以下就可以不用看了

所以我說MQTT是啥？

MQTT（Messa

說明：我打了很久⋯⋯
(;´༎ຶД༎ຶ`)

**Comment by chia-kai-chang** [comment]
已撤銷PyPal的判斷，並給予4點加分
