### ISSUE TITLE
[申請人工文章判定] [資訊量充足] Discussion from yen0224

### ISSUE THREAD

**Issue by yen0224** [NCU-GS4538-Linux/Linux-Community#170]
原文被AI評價為「資訊量充足」
原文網址：https://github.com/NCU-GS4538-Linux/Linux-Community/discussions/164
原文內容：
近期在準備一個網站的開發案，但在利用 docker 準備開發環境的時候，發現即使利用 docker-compose 將檔案資料夾 binding 至 docker 的環境中，仍無法實現 hot-reload 功能，在深入了解 wsl 和 windows 的互動關係之後，才終於找到解決的方式。

## WSL 與 windows 的檔案系統關係
如大家所

說明：

**Comment by chia-kai-chang** [comment]
具有充分實作，以🎉獎勵
