### ISSUE TITLE
[申請人工文章判定]%20[資訊量充足]%20Discussion%20from%20unname0925

### ISSUE THREAD

**Issue by unname0925** [NCU-GS4538-Linux/Linux-Community#39]
原文被AI評價為「資訊量充足」%0A原文網址：https://github.com/NCU-GS4538-Linux/Linux-Community/discussions/38%0A原文內容：%0A%23%20鮮為人知的Excel小工具--巨集%0D%0A我相信各位從小到大，不管是在報告中還是實驗一定都有用過Excel的經歷，而對未經過處理的資料，如%3A2002%2F01%2F01王小明320桃園市中壢區中大路300號,指考分發，我們往往會花費不少時間利用手動將每筆資料的生日、姓名、地址、分發類型區分開來。若當資料不只一筆，而是有10冊，每冊又有100筆資料時，肯定不可能依舊花%0A%0A說明：%0A

**Comment by chia-kai-chang** [comment]
很實用的教學文章，加贈3點
