### ISSUE TITLE
[申請人工文章判定]%20[資訊量充足]%20Discussion%20from%20unname0925

### ISSUE THREAD

**Issue by unname0925** [NCU-GS4538-Linux/Linux-Community#42]
原文被AI評價為「資訊量充足」%0A原文網址：https://github.com/NCU-GS4538-Linux/Linux-Community/discussions/41%0A原文內容：%0A%23%20VS%20Code%20小介紹%0D%0A我想資工、資管或會寫程式的同學對於%2A%2AVisual%20Studio%20Code%2A%2A一定不陌生，但我還是為不知道人簡單介紹一下什麼是%2A%2AVisual%20Studio%20Code%2A%2A。%0D%0A%0D%0AVisual%20Studio%20Code%20是一款由微軟開發的原始碼編輯器，它不只支援%20JavaScript%20，還支援幾乎所有其他的程式語言，許多使用過的開%0A%0A說明：%0A

**Comment by chia-kai-chang** [comment]
很有趣的文章，加贈3點
